// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamProject.DataAccess.DataAccess;

#nullable disable

namespace TeamProject.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260228142757_AddedCollctionImagePropertyField")]
    partial class AddedCollctionImagePropertyField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeamProject.Models.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("TeamProject.Models.Models.Booking", b =>
                {
                    b.Property<string>("BookingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("BookingPrice")
                        .HasColumnType("float");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookingId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("TeamProject.Models.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<int?>("CVC")
                        .HasColumnType("int");

                    b.Property<string>("CreditCardNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Email = "JohnDoe@email.com",
                            Name = "John Doe",
                            PhoneNumber = "0894791234"
                        },
                        new
                        {
                            CustomerId = 2,
                            Email = "JoshBigWilly@email.com",
                            Name = "Josh Wilis",
                            PhoneNumber = "0877778990"
                        },
                        new
                        {
                            CustomerId = 3,
                            Email = "Charlton.United@email.com",
                            Name = "Booby Charlton",
                            PhoneNumber = "0871234567"
                        },
                        new
                        {
                            CustomerId = 4,
                            Email = "Sam_S2005@email.com",
                            Name = "Sam Smith",
                            PhoneNumber = "0870976543"
                        },
                        new
                        {
                            CustomerId = 5,
                            Email = "MarkoPolo@email.com",
                            Name = "Marko Butler",
                            PhoneNumber = "0870998754"
                        },
                        new
                        {
                            CustomerId = 6,
                            Email = "Bobby_D@email.com",
                            Name = "Bob Dillion",
                            PhoneNumber = "0898008420"
                        });
                });

            modelBuilder.Entity("TeamProject.Models.Models.Landlord", b =>
                {
                    b.Property<int>("LandlordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LandlordId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Income")
                        .HasColumnType("float");

                    b.Property<double>("LandlordShare")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("int");

                    b.HasKey("LandlordId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Landlords");
                });

            modelBuilder.Entity("TeamProject.Models.Models.Property", b =>
                {
                    b.Property<int>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyId"));

                    b.Property<string>("DescDescription")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DisplayImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("LandlordId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxGuests")
                        .HasColumnType("int");

                    b.Property<double?>("PricePerNight")
                        .HasColumnType("float");

                    b.Property<string>("PropertyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PropertyId");

                    b.HasIndex("LandlordId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            PropertyId = 1,
                            DescDescription = "Close to ocean",
                            DisplayImage = "\\Images\\Properties\\bearview.jpg",
                            FullDescription = "Beautiful lake view apartment.",
                            Location = "Wicklow",
                            MaxGuests = 4,
                            PricePerNight = 120.0,
                            PropertyType = "Apartment",
                            Status = true,
                            Title = "Bear View Apartment"
                        },
                        new
                        {
                            PropertyId = 2,
                            DescDescription = "Perfect for couples or small families.",
                            DisplayImage = "\\Images\\Properties\\seaview.jpg",
                            FullDescription = "Beautiful modern apartment overlooking the Atlantic Ocean.",
                            Location = "Galway",
                            MaxGuests = 4,
                            PricePerNight = 120.0,
                            PropertyType = "Apartment",
                            Status = true,
                            Title = "Sea View Apartment"
                        },
                        new
                        {
                            PropertyId = 3,
                            DescDescription = "Includes private balcony and skyline views.",
                            DisplayImage = "\\Images\\Properties\\luxurypenthouse.jpg",
                            FullDescription = "Top-floor penthouse in the heart of Dublin city.",
                            Location = "Dublin",
                            MaxGuests = 5,
                            PricePerNight = 350.0,
                            PropertyType = "Penthouse",
                            Status = true,
                            Title = "Luxury City Penthouse"
                        },
                        new
                        {
                            PropertyId = 4,
                            DescDescription = "Peaceful and quiet retreat.",
                            DisplayImage = "\\Images\\Properties\\cozycottage.jpg",
                            FullDescription = "Traditional Irish cottage surrounded by countryside.",
                            Location = "Donegal",
                            MaxGuests = 3,
                            PricePerNight = 90.0,
                            PropertyType = "Cottage",
                            Status = true,
                            Title = "Cozy Country Cottage"
                        },
                        new
                        {
                            PropertyId = 5,
                            DescDescription = "Ideal for business stays or family holidays.",
                            DisplayImage = "\\Images\\Properties\\moderntownhouse.jpg",
                            FullDescription = "Spacious townhouse close to Cork city centre.",
                            Location = "Cork",
                            MaxGuests = 6,
                            PricePerNight = 180.0,
                            PropertyType = "Townhouse",
                            Status = false,
                            Title = "Modern Townhouse"
                        },
                        new
                        {
                            PropertyId = 6,
                            DescDescription = "Great for hiking and outdoor adventures.",
                            DisplayImage = "\\Images\\Properties\\lakefrontcabin.jpg",
                            FullDescription = "Wooden cabin located directly beside the lake.",
                            Location = "Killarney",
                            MaxGuests = 4,
                            PricePerNight = 150.0,
                            PropertyType = "Cabin",
                            Status = true,
                            Title = "Lakefront Cabin"
                        },
                        new
                        {
                            PropertyId = 7,
                            DescDescription = "Private pool and large garden included.",
                            DisplayImage = "\\Images\\Properties\\beachsidevilla.jpg",
                            FullDescription = "Luxury villa steps away from the beach.",
                            Location = "Wexford",
                            MaxGuests = 8,
                            PricePerNight = 400.0,
                            PropertyType = "Villa",
                            Status = true,
                            Title = "Beachside Villa"
                        },
                        new
                        {
                            PropertyId = 8,
                            DescDescription = "Walking distance to shops",
                            DisplayImage = "\\Images\\Properties\\citycenterhouse.jpg",
                            FullDescription = "Modern house in city centre.",
                            Location = "Dublin",
                            MaxGuests = 6,
                            PricePerNight = 200.0,
                            PropertyType = "House",
                            Status = true,
                            Title = "City Centre House"
                        });
                });

            modelBuilder.Entity("TeamProject.Models.Models.PropertyImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyImages");
                });

            modelBuilder.Entity("TeamProject.Models.Models.Landlord", b =>
                {
                    b.HasOne("TeamProject.Models.Models.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("TeamProject.Models.Models.Property", b =>
                {
                    b.HasOne("TeamProject.Models.Models.Landlord", null)
                        .WithMany("Properties")
                        .HasForeignKey("LandlordId");
                });

            modelBuilder.Entity("TeamProject.Models.Models.PropertyImage", b =>
                {
                    b.HasOne("TeamProject.Models.Models.Property", "Property")
                        .WithMany("Images")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("TeamProject.Models.Models.Landlord", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("TeamProject.Models.Models.Property", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
