// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamProject.DataAccess.DataAccess;

#nullable disable

namespace TeamProject.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeamProject.Models.Models.Booking", b =>
                {
                    b.Property<string>("BookingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("BookingPrice")
                        .HasColumnType("float");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookingId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("TeamProject.Models.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<int?>("CVC")
                        .HasColumnType("int");

                    b.Property<string>("CreditCardNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Email = "JohnDoe@email.com",
                            Name = "John Doe",
                            PhoneNumber = "0894791234"
                        },
                        new
                        {
                            CustomerId = 2,
                            Email = "JoshBigWilly@email.com",
                            Name = "Josh Wilis",
                            PhoneNumber = "0877778990"
                        },
                        new
                        {
                            CustomerId = 3,
                            Email = "Charlton.United@email.com",
                            Name = "Booby Charlton",
                            PhoneNumber = "0871234567"
                        },
                        new
                        {
                            CustomerId = 4,
                            Email = "Sam_S2005@email.com",
                            Name = "Sam Smith",
                            PhoneNumber = "0870976543"
                        },
                        new
                        {
                            CustomerId = 5,
                            Email = "MarkoPolo@email.com",
                            Name = "Marko Butler",
                            PhoneNumber = "0870998754"
                        },
                        new
                        {
                            CustomerId = 6,
                            Email = "Bobby_D@email.com",
                            Name = "Bob Dillion",
                            PhoneNumber = "0898008420"
                        });
                });

            modelBuilder.Entity("TeamProject.Models.Models.LandLord", b =>
                {
                    b.Property<int>("LandLordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LandLordId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Income")
                        .HasColumnType("float");

                    b.Property<double>("LandLordShare")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("int");

                    b.HasKey("LandLordId");

                    b.HasIndex("PropertyId");

                    b.ToTable("LandLords");
                });

            modelBuilder.Entity("TeamProject.Models.Models.Property", b =>
                {
                    b.Property<int>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyId"));

                    b.Property<string>("DescDescription")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LandLordId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxGuests")
                        .HasColumnType("int");

                    b.Property<double?>("PricePerNight")
                        .HasColumnType("float");

                    b.Property<string>("PropertyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("PropertyId");

                    b.HasIndex("LandLordId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            PropertyId = 1,
                            DescDescription = "Close to ocean",
                            FullDescription = "Beautiful lake view apartment.",
                            Image = "\\Images\\Properties\\bearview.jpg",
                            Location = "Wicklow",
                            MaxGuests = 4,
                            PricePerNight = 120.0,
                            PropertyType = "Apartment",
                            Title = "Bear View Apartment",
                            status = true
                        },
                        new
                        {
                            PropertyId = 2,
                            DescDescription = "Perfect for couples or small families.",
                            FullDescription = "Beautiful modern apartment overlooking the Atlantic Ocean.",
                            Image = "\\Images\\Properties\\seaview.jpg",
                            Location = "Galway",
                            MaxGuests = 4,
                            PricePerNight = 120.0,
                            PropertyType = "Apartment",
                            Title = "Sea View Apartment",
                            status = true
                        },
                        new
                        {
                            PropertyId = 3,
                            DescDescription = "Includes private balcony and skyline views.",
                            FullDescription = "Top-floor penthouse in the heart of Dublin city.",
                            Image = "\\Images\\Properties\\luxurypenthouse.jpg",
                            Location = "Dublin",
                            MaxGuests = 5,
                            PricePerNight = 350.0,
                            PropertyType = "Penthouse",
                            Title = "Luxury City Penthouse",
                            status = true
                        },
                        new
                        {
                            PropertyId = 4,
                            DescDescription = "Peaceful and quiet retreat.",
                            FullDescription = "Traditional Irish cottage surrounded by countryside.",
                            Image = "\\Images\\Properties\\cozycottage.jpg",
                            Location = "Donegal",
                            MaxGuests = 3,
                            PricePerNight = 90.0,
                            PropertyType = "Cottage",
                            Title = "Cozy Country Cottage",
                            status = true
                        },
                        new
                        {
                            PropertyId = 5,
                            DescDescription = "Ideal for business stays or family holidays.",
                            FullDescription = "Spacious townhouse close to Cork city centre.",
                            Image = "\\Images\\Properties\\moderntownhouse.jpg",
                            Location = "Cork",
                            MaxGuests = 6,
                            PricePerNight = 180.0,
                            PropertyType = "Townhouse",
                            Title = "Modern Townhouse",
                            status = false
                        },
                        new
                        {
                            PropertyId = 6,
                            DescDescription = "Great for hiking and outdoor adventures.",
                            FullDescription = "Wooden cabin located directly beside the lake.",
                            Image = "\\Images\\Properties\\lakefrontcabin.jpg",
                            Location = "Killarney",
                            MaxGuests = 4,
                            PricePerNight = 150.0,
                            PropertyType = "Cabin",
                            Title = "Lakefront Cabin",
                            status = true
                        },
                        new
                        {
                            PropertyId = 7,
                            DescDescription = "Private pool and large garden included.",
                            FullDescription = "Luxury villa steps away from the beach.",
                            Image = "\\Images\\Properties\\beachsidevilla.jpg",
                            Location = "Wexford",
                            MaxGuests = 8,
                            PricePerNight = 400.0,
                            PropertyType = "Villa",
                            Title = "Beachside Villa",
                            status = true
                        },
                        new
                        {
                            PropertyId = 8,
                            DescDescription = "Walking distance to shops",
                            FullDescription = "Modern house in city centre.",
                            Image = "\\Images\\Properties\\citycenterhouse.jpg",
                            Location = "Dublin",
                            MaxGuests = 6,
                            PricePerNight = 200.0,
                            PropertyType = "House",
                            Title = "City Centre House",
                            status = true
                        });
                });

            modelBuilder.Entity("TeamProject.Models.Models.LandLord", b =>
                {
                    b.HasOne("TeamProject.Models.Models.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("TeamProject.Models.Models.Property", b =>
                {
                    b.HasOne("TeamProject.Models.Models.LandLord", null)
                        .WithMany("Properties")
                        .HasForeignKey("LandLordId");
                });

            modelBuilder.Entity("TeamProject.Models.Models.LandLord", b =>
                {
                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
